export const siteConfig = {
  blogName: 'binary01.me',
  author: 'Jinsoo Lee',
  homeTitle: "Jinsoo's Blog",
  introName: '@Jinsoo Lee(3o3/Web)',
  introDesc: 'Hi~👋 🧑🏻‍💻',
  seoDefaultDesc: '웹 프론트엔드 개발자 진수입니다!',
  url: 'https://binary01.me',
  github: '01-binary',
  linkedIn: 'jinsoo-lee-b9a102188',
  mail: 'binary01@kakao.com',
  googleSiteVerification: '8ASKSU1Tj6Kc3H3qTnlRiVMn6F6PsLVsKU_RqsS0MfA',
  naverSiteVerification: 'c5c5ff5b071ac345b5e4eda384975545289762d6',
  giscus: {
    repo: '01-binary/binary01.me-notion-cms',
    repoId: 'R_kgDOIj2fYg',
    category: 'Announcements',
    categoryId: 'DIC_kwDOIj2fYs4CfJiI',
    theme: 'preferred_color_scheme',
  },
};
